export const jobs = [
  {
    id: 1,
    company: "Photosnap",
    logo: "/images/photosnap.svg",
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    role: "Frontend",
    level: "Senior",
    postedAt: "1d ago",
    contract: "FullTime",
    location: "USA Only",
    languages: ["HTML", "CSS", "JavaScript"],
    tools: [],
    tags: ["Frontend", "Senior", "FullTime", "HTML", "CSS", "JavaScript"],
  },
  {
    id: 2,
    company: "Manage",
    logo: "/images/manage.svg",
    new: true,
    featured: true,
    position: "Fullstack Developer",
    role: "Fullstack",
    level: "MidLevel",
    postedAt: "1d ago",
    contract: "PartTime",
    location: "Remote",
    languages: ["Python"],
    tools: ["React"],
    tags: ["Fullstack", "MidLevel", "PartTime", "Python", "React"],
  },
  {
    id: 3,
    company: "Account",
    logo: "/images/account.svg",
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2d ago",
    contract: "PartTime",
    location: "USA Only",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
    tags: ["Frontend", "Junior", "PartTime", "JavaScript", "React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: "/images/myhome.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA Only",
    languages: ["CSS", "JavaScript"],
    tools: [],
    tags: ["Frontend", "Junior", "Contract", "CSS", "JavaScript"],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: "/images/loop-studios.svg",
    new: false,
    featured: false,
    position: "Software Engineer",
    role: "Fullstack",
    level: "MidLevel",
    postedAt: "1w ago",
    contract: "FullTime",
    location: "Worldwide",
    languages: ["JavaScript", "Ruby"],
    tools: ["Sass"],
    tags: ["Fullstack", "MidLevel", "FullTime", "JavaScript", "Ruby", "Sass"],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: "/images/faceit.svg",
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    role: "Backend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "FullTime",
    location: "UK Only",
    languages: ["Ruby"],
    tools: ["RoR"],
    tags: ["Backend", "Junior", "FullTime", "Ruby", "RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: "/images/shortly.svg",
    new: false,
    featured: false,
    position: "Junior Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "FullTime",
    location: "Worldwide",
    languages: ["HTML", "JavaScript"],
    tools: ["Sass"],
    tags: ["Frontend", "Junior", "FullTime", "HTML", "JavaScript", "Sass"],
  },
  {
    id: 8,
    company: "Insure",
    logo: "/images/insure.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "FullTime",
    location: "USA Only",
    languages: ["JavaScript"],
    tools: ["Vue", "Sass"],
    tags: ["Frontend", "Junior", "FullTime", "JavaScript", "Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: "/images/eyecam-co.svg",
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    role: "Fullstack",
    level: "MidLevel",
    postedAt: "3w ago",
    contract: "FullTime",
    location: "Worldwide",
    languages: ["JavaScript", "Python"],
    tools: ["Django"],
    tags: [
      "Fullstack",
      "MidLevel",
      "FullTime",
      "JavaScript",
      "Python",
      "Django",
    ],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: "/images/the-air-filter-company.svg",
    new: false,
    featured: false,
    position: "Front-end Dev",
    role: "Frontend",
    level: "Junior",
    postedAt: "1mo ago",
    contract: "PartTime",
    location: "Worldwide",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
    tags: ["Frontend", "Junior", "PartTime", "JavaScript", "React", "Sass"],
  },
]
